### ISSUE TITLE
[System.Security.Principal.NTAccount] does not contain a method named 'StartsWith'

### ISSUE THREAD

**Issue by zeclab** [santysq/Get-EffectiveAccess#1]
Hi,
Getting the following error message when trying to run the script:
`Where-Object : Method invocation failed because [System.Security.Principal.NTAccount] does not contain a method named
'StartsWith'.`
`At line:81 char:19`
`+ ...   $result | Where-Object { -not $($_.IdentityReference.StartsWith('S- ...`
`+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [Where-Object], RuntimeException`
`    + FullyQualifiedErrorId : MethodNotFound,Microsoft.PowerShell.Commands.WhereObjectCommand`

I found that if I change line 81 from:
`$result | Where-Object { -not $_.IdentityReference.StartsWith('S-1-5-21') } |`

To:
`$result | Where-Object { -not $_.IdentityReference.Value.StartsWith('S-1-5-21') } |`

It then works correctly.

Cheers

**Comment by santisq** [comment]
@zeclab that's an excellent catch and a typo on my side. Would you like to create a PR to fix it?

**Comment by zeclab** [comment]
I'm a bit new to this whole git lark but I'll give it a go.

**Comment by santisq** [comment]
@zeclab I have decided to update the code base for this function and to remove the `switch`, updated version can be found here https://stackoverflow.com/a/67698076/15339544 didn't have time to update it on GH. Thank you for letting me know about the typo!

**Comment by santisq** [comment]
@zeclab Commit [`77c0b6f36a9e611d6629df12a28a15053eca7294`](https://github.com/santysq/Get-EffectiveAccess/commit/77c0b6f36a9e611d6629df12a28a15053eca7294) fixes this issue. Thanks!
