### ISSUE TITLE
Get effective permissions for a user on a network share?

### ISSUE THREAD

**Issue by drt1** [santysq/Get-EffectiveAccess#2]
Hello,

is it somehow possible to use your module to get the effective permission set on a network share for a given user?

Thinking of something pseudo-code like this:
`$user = Read-Host "Enter username"
$shares = "\\server1\shareA","\\server2\shareB"

foreach ($share in $shares) {
    Get-EffectiveAccess -Path $share -Principal $user
}`

thanks!

**Comment by santisq** [comment]
hi @drt1 the function in this repo is a simple function that helps translating Access Rules from Active Directory into human readable rules. It is not meant for NTFS ACLs. You may want to have a look at https://github.com/raandree/NTFSSecurity heard its very good but did not try it personally
